import type { InferGetStaticPropsType } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { client } from "../util/pokemon-client";
import { FixedSizeList } from "react-window";
import AutoSizer from "react-virtualized-auto-sizer";
import type { Pokemon } from "pokenode-ts";

export const getStaticProps = async () => {
  const fetchAllPokemon = Array.from({ length: 151 }).map((_, idx) =>
    client.getPokemonById(idx + 1)
  );

  const pokemon = await Promise.all(fetchAllPokemon);

  return {
    props: {
      pokemon,
    },
  };
};

const PokemonRow = ({
  index,
  style,
  data,
}: {
  index: number;
  style: any;
  data: Pokemon[];
}) => {
  const pokemon = data[index];

  return (
    <div
      className={index % 2 ? styles.listItemOdd : styles.listItemEven}
      style={style}
    >
      {pokemon.sprites.front_default ? (
        <Image
          src={pokemon.sprites.front_default}
          alt={pokemon.name}
          width={100}
          height={100}
        />
      ) : null}

      {pokemon.name}
    </div>
  );
};

function Home({ pokemon }: InferGetStaticPropsType<typeof getStaticProps>) {
  console.log(pokemon);

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AutoSizer>
          {({ height, width }) => (
            <FixedSizeList
              className="list"
              width={width}
              height={height}
              itemCount={pokemon.length}
              itemData={pokemon}
              itemSize={100}
            >
              {({ style, data, index }) => (
                <PokemonRow style={style} data={data} index={index} />
              )}
            </FixedSizeList>
          )}
        </AutoSizer>
      </main>
    </div>
  );
}

export default Home;
